<a href="https://colab.research.google.com/github/Himanshi143/Machine-Learning/blob/main/Lec-62/Ridge_Regression_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simple Ridge Regression

In [1]:
import numpy as np
from sklearn.datasets import load_diabetes,make_regression

In [2]:
X,y=make_regression(n_samples=100,n_features=1,n_informative=1,n_targets=1,noise=20,random_state=13)

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [4]:
from sklearn.linear_model import Ridge

In [5]:
R=Ridge(alpha=0.001,solver='cholesky')

In [6]:
R.fit(X_train,y_train)

Ridge(alpha=0.001, solver='cholesky')

In [7]:
y_pred=R.predict(X_test)

In [8]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6345175361868379

In [9]:
R.coef_

array([28.12560165])

In [10]:
R.intercept_

-2.2709956027916407

In [11]:
class MeraRidge:
  def __init__(self,alpha=0.1):
    self.alpha=alpha
    self.coef_=None
    self.intercept_=None
  def fit(self,X_train,y_train):
    num=0
    den=0
    for i in range(X_train.shape[0]):
      num+=((X_train[i]-np.mean(X_train))*(y_train[i]-np.mean(y_train)))
      den+=(X_train[i]-np.mean(X_train))**2
    self.coef_=num/(den+self.alpha)
    self.intercept_=np.mean(y_train)-self.coef_*np.mean(X_train)
  def predict(self,X_test):
    return self.coef_*X_test+self.intercept_

In [12]:
mr=MeraRidge(alpha=0.001)

In [13]:
mr.fit(X_train,y_train)

In [14]:
y_pred1=mr.predict(X_test)

In [15]:
r2_score(y_test,y_pred1)

0.6345175361868378

In [16]:
mr.coef_

array([28.12560165])

In [17]:
mr.intercept_

array([-2.2709956])

# Multiple Ridge Regression

In [18]:
from sklearn.datasets import load_diabetes
X,y=load_diabetes(return_X_y=True)

In [20]:
X.shape

(442, 10)

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [22]:
R1=Ridge(alpha=0.001,solver='cholesky')

In [23]:
R1.fit(X_train,y_train)

Ridge(alpha=0.001, solver='cholesky')

In [24]:
y_pred1=R1.predict(X_test)

In [25]:
r2_score(y_test,y_pred1)

0.4408617113920028

In [27]:
class MeraMridge:
  def __init__(self,alpha=0.1):
    self.alpha=alpha
    self.coef_=None
    self.intercept_=None
  def fit(self,x_train,y_train):
    x_train=np.insert(x_train,0,1,axis=1)
    I=np.identity(x_train.shape[1])
    I[0][0]=0
    result=np.linalg.inv(np.dot(x_train.T,x_train)+self.alpha*I).dot(x_train.T).dot(y_train)
    self.intercept_=result[0]
    self.coef_=result[1:]
  def predict(self,x_test):
    return np.dot(x_test,self.coef_)+self.intercept_

In [28]:
mr1=MeraMridge(alpha=0.001)

In [29]:
mr1.fit(X_train,y_train)

In [30]:
y_pred3=mr1.predict(X_test)

In [31]:
r2_score(y_test,y_pred3)

0.44086171139200325

In [32]:
mr1.coef_

array([  -8.76148719, -204.31340446,  518.38060848,  339.96792595,
       -787.7005103 ,  475.28218117,  106.79525299,  114.62926497,
        819.74572278,   52.87334942])

In [33]:
mr1.intercept_

151.88534076475435