<a href="https://colab.research.google.com/github/Himanshi143/Machine-Learning-By-Campusx/blob/main/Day-29/day_29_without_pipelines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.impute import SimpleImputer

In [ ]:
df=pd.read_csv('/content/train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
df=

In [ ]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df.drop('Survived',axis=1),df['Survived'],test_size=0.2)
x_train.head()

Pclass   Sex   Age  SibSp  Parch     Fare Embarked
606       3  male  30.0      0      0   7.8958        S
248       1  male  37.0      1      1  52.5542        S
452       1  male  30.0      0      0  27.7500        C
490       3  male   NaN      1      0  19.9667        S
857       1  male  51.0      0      0  26.5500        S

In [ ]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
si_age=SimpleImputer()
si_embarked=SimpleImputer(strategy='most_frequent')
x_train_age=si_age.fit_transform(x_train[['Age']])
x_train_embarked=si_embarked.fit_transform(x_train[['Embarked']])
x_test_age=si_age.transform(x_test[['Age']])
x_test_embarked=si_embarked.transform(x_test[['Embarked']])

In [ ]:
import pandas as pd

# Convert the NumPy array back to a Pandas DataFrame
x_train_embarked_df = pd.DataFrame(x_train_embarked, columns=['Embarked'])

# Now you can use isnull()
x_train_embarked_df.isnull().sum()

Embarked    0
dtype: int64

In [ ]:
ohe_sex=OneHotEncoder(sparse=False,handle_unknown='ignore')
x_train_sex=ohe_sex.fit_transform(x_train[['Sex']])
x_test_sex=ohe_sex.transform(x_test[['Sex']])

ohe_em=OneHotEncoder(sparse=False,handle_unknown='ignore')
x_train_embarked=ohe_em.fit_transform(x_train_embarked)
x_test_embarked=ohe_em.transform(x_test_embarked)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
x_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [ ]:
x_train_rem=x_train.drop(['Sex','Embarked','Age'],axis=1)
x_test_rem=x_test.drop(['Sex','Embarked','Age'],axis=1)

In [ ]:
x_train_t=np.concatenate((x_train_rem,x_train_sex,x_train_embarked,x_train_age),axis=1)
x_test_t=np.concatenate((x_test_rem,x_test_sex,x_test_embarked,x_test_age),axis=1)


In [ ]:
x_train_t

array([[ 3.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 30.        ],
       [ 1.        ,  1.        ,  1.        , ...,  0.        ,
         1.        , 37.        ],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 30.        ],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 49.        ],
       [ 2.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 36.        ],
       [ 3.        ,  0.        ,  0.        , ...,  1.        ,
         0.        , 29.95826011]])

In [ ]:
clf=DecisionTreeClassifier()
clf.fit(x_train_t,y_train)
y_pred=clf.predict(x_test_t)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7653631284916201

In [ ]:
import pickle

In [ ]:
pickle.dump(ohe_sex,open('ohe_sex.pkl','wb'))
pickle.dump(ohe_em,open('ohe_embarked.pkl','wb'))
pickle.dump(clf,open('clf.pkl','wb'))

# Website

In [ ]:
import pickle
import numpy as np

In [ ]:
ohe_sex=pickle.load(open('ohe_sex.pkl','rb'))
ohe_em=pickle.load(open('ohe_embarked.pkl','rb'))
clf=pickle.load(open('clf.pkl','rb'))

In [ ]:
t_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object)

In [ ]:
t_input

array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object)

In [ ]:
t_input_sex=ohe_sex.transform([[t_input[1]]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [ ]:
t_input_sex

array([[0., 1.]])

In [ ]:
t_input_em=ohe_em.transform([[t_input[-1]]])

In [ ]:
t_input_em

array([[0., 0., 1.]])

In [ ]:
t_input_age=np.array([[t_input[2]]])

In [ ]:
t_rem=np.concatenate(([t_input[[0,3,4,5]]],t_input_sex,t_input_em,t_input_age),axis=1)

In [ ]:
t_rem.shape

(1, 10)

In [ ]:
clf.predict(t_rem)

array([0])