<a href="https://colab.research.google.com/github/Himanshi143/Machine-Learning-By-Campusx/blob/main/Day-28/day_28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np

In [11]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df=pd.read_csv('/content/covid_toy.csv')
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [19]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [26]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [17]:
df['cough'].value_counts().sum()

100

In [13]:
df.shape

(100, 6)

In [14]:
df['gender'].value_counts().sum()

100

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(df.drop('has_covid',axis=1),df['has_covid'],test_size=0.2)

In [20]:
x_train

age  gender  fever   cough       city
23   80  Female   98.0    Mild      Delhi
71   75  Female  104.0  Strong      Delhi
4    65  Female  101.0    Mild     Mumbai
44   20    Male  102.0  Strong      Delhi
43   22  Female   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
25   23    Male    NaN    Mild     Mumbai
94   79    Male    NaN  Strong    Kolkata
63   10    Male  100.0    Mild  Bangalore
24   13  Female  100.0  Strong    Kolkata
50   19    Male  101.0    Mild      Delhi

[80 rows x 5 columns]

In [22]:
si=SimpleImputer()
x_train_si=si.fit_transform(x_train[['fever']])
x_test_si=si.transform(x_test[['fever']])
x_train_si

array([[ 98.        ],
       [104.        ],
       [101.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [102.        ],
       [102.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [100.        ],
       [ 98.        ],
       [100.95833333],
       [ 99.        ],
       [103.        ],
       [103.        ],
       [100.        ],
       [100.95833333],
       [101.        ],
       [100.        ],
       [100.        ],
       [103.        ],
       [102.        ],
       [ 99.        ],
       [103.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [104.        ],
       [100

In [24]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_oe=oe.fit_transform(x_train[['cough']])
x_test_oe=oe.transform(x_test[['cough']])
x_train_oe

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],

In [25]:
ohe=OneHotEncoder(sparse=False,drop='first')
x_train_ohe=ohe.fit_transform(x_train[['gender','city']])
x_test_ohe=ohe.transform(x_test[['gender','city']])
x_train_ohe

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],


In [37]:
x_train_age=np.array(x_train.iloc[:,0])[:,np.newaxis]
x_test_age=np.array(x_test.iloc[:,0])[:,np.newaxis]
x_train_age

array([[80],
       [75],
       [65],
       [20],
       [22],
       [65],
       [16],
       [42],
       [51],
       [24],
       [23],
       [38],
       [ 6],
       [64],
       [ 5],
       [49],
       [83],
       [12],
       [49],
       [ 8],
       [15],
       [31],
       [73],
       [80],
       [ 5],
       [82],
       [72],
       [48],
       [83],
       [ 5],
       [71],
       [19],
       [19],
       [47],
       [16],
       [82],
       [66],
       [69],
       [81],
       [14],
       [73],
       [69],
       [54],
       [20],
       [42],
       [74],
       [82],
       [25],
       [59],
       [64],
       [27],
       [60],
       [84],
       [65],
       [51],
       [56],
       [19],
       [46],
       [11],
       [33],
       [17],
       [14],
       [34],
       [27],
       [27],
       [24],
       [55],
       [65],
       [11],
       [64],
       [42],
       [34],
       [38],
       [50],
       [26],
       [23],
       [79],

In [39]:
transformed=np.concatenate((x_train_age,x_train_si,x_train_oe,x_train_ohe),axis=1)
transformed.shape

(80, 7)

Simple Method

In [40]:
from sklearn.compose import ColumnTransformer

In [43]:
ct=ColumnTransformer(transformers=[
    ('t1',SimpleImputer(),['fever']),
    ('t2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('t3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')# in remainder drop or passthrough

In [45]:
ct.fit_transform(x_train).shape

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 7)

In [46]:
ct.transform(x_test).shape

(20, 7)