<a href="https://colab.research.google.com/github/Himanshi143/Machine-Learning/blob/main/Day-55/My_own_Multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn.datasets import load_diabetes

In [4]:
X,y=load_diabetes(return_X_y=True)

In [5]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [6]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [9]:
x_train.shape

(353, 10)

In [10]:
y_train.shape

(353,)

In [11]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [12]:
lr.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pred=lr.predict(x_test)

In [14]:
lr.coef_

array([ -61.16145109, -278.09329999,  549.31594809,  248.61746109,
       -901.33070006,  641.56582267,  118.6183811 ,  183.72017536,
        771.51652783,   75.66202357])

In [15]:
lr.intercept_

151.81185736495542

**My own Multiple Linear Regression**

In [27]:
class MeraLR:
  def __init__(self):
    self.coef_=None
    self.intercept_=None
  def fit(self,X_train,Y_train):
    X_train=np.insert(X_train,0,1,axis=1)
    betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(Y_train)
    self.intercept_=betas[0]
    self.coef_=betas[1:]
  def predict(self,X_test):
    Y_pred=np.dot(X_test,self.coef_)+self.intercept_
    return Y_pred

In [28]:
MeraLr=MeraLR()

In [29]:
MeraLr.fit(x_train,y_train)

In [30]:
MeraLr.predict(x_test)

array([191.97701273, 193.07496222, 239.67843438, 148.08010925,
        63.19024521, 225.39938525, 246.12162776, 120.735915  ,
       166.54083671, 227.14747249, 127.65820133, 158.31146284,
       201.15852228, 113.91239037, 111.28298764, 161.08262013,
       116.1199729 , 192.79795685, 224.5437426 ,  77.63772262,
       179.02549248,  92.79622236, 200.43982908, 152.80779069,
       153.0982724 , 147.3396745 , 244.22255841, 161.75970509,
       153.64850973,  93.05395519,  44.9848808 , 150.09409866,
        96.69808117, 177.53815553, 224.66606419, 110.17366371,
       190.52591455, 128.28484177, 139.28935342, 260.40713429,
       116.01182308, 170.24679594, 144.17110155,  85.21741118,
       122.53627301,  83.52747097,  78.60372377, 247.00491147,
       201.67981251, 161.77193663, 198.53765063, 155.92124332,
        66.49547029,  84.64681639, 223.20063612, 125.04536317,
       205.47229046,  66.71663398, 253.33783761, 102.55426262,
       119.11609504, 189.62931267, 198.24145013, 208.11

In [31]:
MeraLr.coef_

array([ -61.16145109, -278.09329999,  549.31594809,  248.61746109,
       -901.33070006,  641.56582267,  118.6183811 ,  183.72017536,
        771.51652783,   75.66202357])

In [32]:
MeraLr.intercept_

151.81185736495553