<a href="https://colab.research.google.com/github/Himanshi143/Machine-Learning-By-Campusx/blob/main/Day-11/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

0D/SCALAR

In [4]:
arr=np.array(2)
print(arr)
print("Dimension:",arr.ndim)

2
Dimension: 0


1D/VECTOR

In [5]:
arr=np.array([2,3])
print(arr)
print("Dimension:",arr.ndim)

[2 3]
Dimension: 1


2D/MATRICES

In [6]:
arr=np.array([[1,2,3],[2,3,4]])
print(arr)
print("Dimension:",arr.ndim)

[[1 2 3]
 [2 3 4]]
Dimension: 2


3D

In [7]:
arr=np.array([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])
print(arr)
print("Dimension:",arr.ndim)

[[[1 2 3]
  [2 3 4]]

 [[1 2 3]
  [2 3 4]]]
Dimension: 3
